q_env:
  Q_RUNTIME_TOTAL_FLOOR: 0.10
  Q_DEFAULT_DISABLE_GOVERNORS: heartbeat_scaler
  Q_ENABLE_ASSET_CLASS_DIVERSIFICATION: 1
  Q_CREDIT_LEADLAG_STRENGTH: 0.55
  Q_CROSS_SECTIONAL_MOMENTUM_STRENGTH: 0.26
  Q_MICROSTRUCTURE_STRENGTH: 0.30
  Q_CALENDAR_EVENT_STRENGTH: 0.18
  Q_CONFIRMATION_FLOOR: 0.05
  Q_CONFIRMATION_RAMP_DAYS: 1.0
  Q_CONFIRMATION_FAST_CONFIRM: 1
  Q_REGIME_COUNCIL_ENABLED: 0
  Q_REGIME_COUNCIL_LOOKBACK: 63
  Q_REGIME_COUNCIL_MIN_REGIME_DAYS: 60
  Q_REGIME_COUNCIL_DYNAMIC_CLASSIFIER: 1
  Q_BANDIT_TYPE: thompson
  Q_THOMPSON_DECAY: 0.992
  Q_THOMPSON_MAGNITUDE_SCALING: 1
  Q_DNA_CONVERGENCE_WINDOW: 48
  Q_DNA_CONVERGENCE_TOPK: 20
  Q_DNA_CONVERGENCE_LOOKBACK: 14
  Q_DNA_CONVERGENCE_SMOOTH_ALPHA: 0.25
  Q_DNA_CONVERGENCE_DIVERGENCE_THRESHOLD: 0.04
  Q_ADAPTIVE_SIGNAL_MAX_IMFS: 6
  Q_ADAPTIVE_SIGNAL_TREND_PERIOD_THRESHOLD: 96
  Q_LEADLAG_WINDOW: 84
  Q_LEADLAG_LAG: 1
  Q_FRACTAL_EFF_LOOKBACK: 14
  Q_VOL_FORECAST_TRAIN_WINDOW: 378
  Q_VOL_FORECAST_STEP: 14
  Q_VOL_FORECAST_OVERLAY_STRENGTH: 0.24
  Q_VOL_FORECAST_OVERLAY_FLOOR: 0.70
  Q_VOL_FORECAST_OVERLAY_CEIL: 1.30
  Q_ENTROPY_SIZING_STRENGTH: 0.95
  Q_ENTROPY_SIZING_FLOOR: 0.25
  Q_ENTROPY_SIZING_CEIL: 1.60
  Q_REGIME_TRANSITION_STRENGTH: 1.10
  Q_SYNTHETIC_VOL_OVERLAY_STRENGTH: 0.90
  Q_CALENDAR_MASK_ENABLED: 1
  Q_CALENDAR_MASK_BETA: 0.75
  Q_CALENDAR_MASK_FLOOR: 0.70
  Q_CALENDAR_MASK_CEIL: 1.20
  Q_CALENDAR_MASK_STRENGTH: 1.1
  Q_HIVE_CONVICTION_THRESHOLD: 0.35
  Q_HIVE_CONVICTION_FLOOR: 0.25
  Q_HIVE_CONVICTION_CEIL: 1.15
  Q_META_GATE_ADAPTIVE: 1
  Q_META_GATE_HIT_RATE_WINDOW: 20
  Q_META_GATE_ADAPTIVE_TIGHTEN_STEP: 0.05
  Q_META_GATE_ADAPTIVE_LOOSEN_STEP: 0.03
  Q_META_GATE_ADAPTIVE_THRESHOLD_MIN: 0.40
  Q_META_GATE_ADAPTIVE_THRESHOLD_MAX: 0.66
  Q_PROMOTION_REQUIRE_COST_STRESS: 1
  Q_PROMOTION_REQUIRE_EXTERNAL_HOLDOUT: 0
  Q_COST_STRESS_MIN_ROBUST_SHARPE: 0.85
  Q_COST_STRESS_MIN_ROBUST_HIT: 0.47
  Q_COST_STRESS_MAX_ABS_MDD: 0.15
  Q_RUNTIME_SEARCH_GOVERNOR_TRAIN_FRAC: 0.75
  Q_RUNTIME_SEARCH_GOVERNOR_HOLDOUT_MIN: 252
  Q_RUNTIME_SEARCH_GOVERNOR_VALIDATION_MIN_ROWS: 252
  Q_GOVERNOR_WALKFORWARD_ENABLED: 0
  Q_GOVERNOR_WF_TRAIN_MIN: 630
  Q_GOVERNOR_WF_TEST_SIZE: 42
  Q_GOVERNOR_WF_MAX_FOLDS: 16

aion_env:
  AION_TRADING_MODE: day_skimmer
  AION_HIST_BAR_SIZE: 1 min
  AION_HIST_DURATION: 3 D
  AION_HIST_USE_RTH: 0
  AION_LOOP_SECONDS: 10
  AION_MAX_TRADES_PER_DAY: 35
  AION_MAX_OPEN_POSITIONS: 10
  AION_RISK_PER_TRADE: 0.01
  AION_INTRADAY_VP_BINS: 24
  AION_ENTRY_THRESHOLD_LONG: 0.62
  AION_ENTRY_THRESHOLD_SHORT: 0.62
  AION_PARTIAL_PROFIT_ENABLED: 1
  AION_PARTIAL_PROFIT_R_MULTIPLE: 0.8
  AION_PARTIAL_PROFIT_FRACTION: 0.50
  AION_TRAILING_STOP_ENABLED: 1
  AION_TRAILING_STOP_ATR_MULTIPLE: 1.5
  AION_STOP_ATR_LONG: 2.0
  AION_STOP_ATR_SHORT: 1.5
  AION_STOP_VOL_ADAPTIVE: 1
  AION_STOP_VOL_LOOKBACK: 20
  AION_STOP_VOL_EXPANSION_MULT: 1.3
  AION_SKIMMER_WATCHLIST_MIN_AVG_VOLUME: 12000000
  AION_SKIMMER_WATCHLIST_MAX_SPREAD_BPS: 4.0
  AION_SKIMMER_WATCHLIST_REQUIRE_SPREAD: 1
  AION_SKIMMER_WATCHLIST_MIN_ATR_5M: 0.20
  AION_SKIMMER_WATCHLIST_MAX_SYMBOLS: 15
  AION_SKIMMER_WATCHLIST_REFRESH_MIN: 15
  AION_SKIMMER_WATCHLIST_Q_BIAS_THRESHOLD: 0.25
  AION_SKIMMER_WATCHLIST_EARNINGS_DAYS: 1
  AION_SKIMMER_WATCHLIST_DURATION: 3 D
  AION_SKIMMER_WATCHLIST_BARS_CACHE_SEC: 45
  AION_TELEMETRY_ENABLED: 1
  AION_TELEMETRY_SUMMARY_WINDOW: 20
