q_env:
  Q_RUNTIME_TOTAL_FLOOR: 0.10
  Q_DEFAULT_DISABLE_GOVERNORS: heartbeat_scaler
  Q_ENABLE_ASSET_CLASS_DIVERSIFICATION: 1
  Q_CREDIT_LEADLAG_STRENGTH: 0.55
  Q_CROSS_SECTIONAL_MOMENTUM_STRENGTH: 0.26
  Q_MICROSTRUCTURE_STRENGTH: 0.30
  Q_CALENDAR_EVENT_STRENGTH: 0.18
  Q_CONFIRMATION_FLOOR: 0.05
  Q_CONFIRMATION_RAMP_DAYS: 1.0
  Q_CONFIRMATION_FAST_CONFIRM: 1
  Q_REGIME_COUNCIL_ENABLED: 0
  Q_REGIME_COUNCIL_LOOKBACK: 63
  Q_REGIME_COUNCIL_MIN_REGIME_DAYS: 60
  Q_DNA_CONVERGENCE_WINDOW: 48
  Q_DNA_CONVERGENCE_TOPK: 20
  Q_DNA_CONVERGENCE_LOOKBACK: 14
  Q_DNA_CONVERGENCE_SMOOTH_ALPHA: 0.25
  Q_DNA_CONVERGENCE_DIVERGENCE_THRESHOLD: 0.04
  Q_CALENDAR_MASK_ENABLED: 1
  Q_CALENDAR_MASK_BETA: 0.75
  Q_CALENDAR_MASK_FLOOR: 0.70
  Q_CALENDAR_MASK_CEIL: 1.20
  Q_CALENDAR_MASK_STRENGTH: 1.1
  Q_HIVE_CONVICTION_THRESHOLD: 0.35
  Q_HIVE_CONVICTION_FLOOR: 0.25
  Q_HIVE_CONVICTION_CEIL: 1.15
  Q_META_GATE_ADAPTIVE: 1
  Q_META_GATE_HIT_RATE_WINDOW: 20
  Q_META_GATE_ADAPTIVE_TIGHTEN_STEP: 0.05
  Q_META_GATE_ADAPTIVE_LOOSEN_STEP: 0.03
  Q_META_GATE_ADAPTIVE_THRESHOLD_MIN: 0.40
  Q_META_GATE_ADAPTIVE_THRESHOLD_MAX: 0.66
  Q_PROMOTION_REQUIRE_COST_STRESS: 1
  Q_PROMOTION_REQUIRE_EXTERNAL_HOLDOUT: 0
  Q_COST_STRESS_MIN_ROBUST_SHARPE: 0.85
  Q_COST_STRESS_MIN_ROBUST_HIT: 0.47
  Q_COST_STRESS_MAX_ABS_MDD: 0.15
  Q_RUNTIME_SEARCH_GOVERNOR_TRAIN_FRAC: 0.75
  Q_RUNTIME_SEARCH_GOVERNOR_HOLDOUT_MIN: 252

aion_env:
  AION_TRADING_MODE: day_skimmer
  AION_HIST_BAR_SIZE: 1 min
  AION_HIST_DURATION: 3 D
  AION_HIST_USE_RTH: 0
  AION_LOOP_SECONDS: 10
  AION_MAX_TRADES_PER_DAY: 35
  AION_MAX_OPEN_POSITIONS: 10
  AION_RISK_PER_TRADE: 0.01
  AION_ENTRY_THRESHOLD_LONG: 0.62
  AION_ENTRY_THRESHOLD_SHORT: 0.62
  AION_PARTIAL_PROFIT_ENABLED: 1
  AION_PARTIAL_PROFIT_R_MULTIPLE: 0.8
  AION_PARTIAL_PROFIT_FRACTION: 0.50
  AION_TRAILING_STOP_ENABLED: 1
  AION_TRAILING_STOP_ATR_MULTIPLE: 1.5
