q_env:
  Q_RUNTIME_TOTAL_FLOOR: 0.10
  Q_DEFAULT_DISABLE_GOVERNORS: heartbeat_scaler
  Q_ENABLE_ASSET_CLASS_DIVERSIFICATION: 1
  Q_CREDIT_LEADLAG_STRENGTH: 0.55
  Q_MICROSTRUCTURE_STRENGTH: 0.30
  Q_CALENDAR_EVENT_STRENGTH: 0.18
  Q_PROMOTION_REQUIRE_COST_STRESS: 1
  Q_COST_STRESS_MIN_ROBUST_SHARPE: 0.85
  Q_COST_STRESS_MIN_ROBUST_HIT: 0.47
  Q_COST_STRESS_MAX_ABS_MDD: 0.15

aion_env:
  AION_TRADING_MODE: day_skimmer
  AION_HIST_BAR_SIZE: 1 min
  AION_HIST_DURATION: 3 D
  AION_HIST_USE_RTH: 0
  AION_LOOP_SECONDS: 10
  AION_MAX_TRADES_PER_DAY: 35
  AION_MAX_OPEN_POSITIONS: 10
  AION_RISK_PER_TRADE: 0.01
  AION_ENTRY_THRESHOLD_LONG: 0.62
  AION_ENTRY_THRESHOLD_SHORT: 0.62
