q_env:
  Q_RUNTIME_TOTAL_FLOOR: 0.18
  Q_DEFAULT_DISABLE_GOVERNORS: global_governor,heartbeat_scaler
  Q_ENABLE_ASSET_CLASS_DIVERSIFICATION: 1
  Q_CREDIT_LEADLAG_STRENGTH: 0.20
  Q_CROSS_SECTIONAL_MOMENTUM_STRENGTH: 0.10
  Q_MICROSTRUCTURE_STRENGTH: 0.12
  Q_CALENDAR_EVENT_STRENGTH: 0.08
  Q_CONFIRMATION_FLOOR: 0.25
  Q_CONFIRMATION_RAMP_DAYS: 3.0
  Q_CONFIRMATION_FAST_CONFIRM: 1
  Q_REGIME_COUNCIL_ENABLED: 0
  Q_REGIME_COUNCIL_LOOKBACK: 63
  Q_REGIME_COUNCIL_MIN_REGIME_DAYS: 60
  Q_DNA_CONVERGENCE_WINDOW: 84
  Q_DNA_CONVERGENCE_TOPK: 12
  Q_DNA_CONVERGENCE_LOOKBACK: 28
  Q_DNA_CONVERGENCE_SMOOTH_ALPHA: 0.12
  Q_DNA_CONVERGENCE_DIVERGENCE_THRESHOLD: 0.06
  Q_CALENDAR_MASK_ENABLED: 1
  Q_CALENDAR_MASK_BETA: 0.45
  Q_CALENDAR_MASK_FLOOR: 0.80
  Q_CALENDAR_MASK_CEIL: 1.10
  Q_CALENDAR_MASK_STRENGTH: 0.9
  Q_HIVE_CONVICTION_THRESHOLD: 0.45
  Q_HIVE_CONVICTION_FLOOR: 0.35
  Q_HIVE_CONVICTION_CEIL: 1.08
  Q_META_GATE_ADAPTIVE: 1
  Q_META_GATE_HIT_RATE_WINDOW: 20
  Q_META_GATE_ADAPTIVE_TIGHTEN_STEP: 0.03
  Q_META_GATE_ADAPTIVE_LOOSEN_STEP: 0.015
  Q_META_GATE_ADAPTIVE_THRESHOLD_MIN: 0.45
  Q_META_GATE_ADAPTIVE_THRESHOLD_MAX: 0.70
  Q_PROMOTION_REQUIRE_COST_STRESS: 1
  Q_PROMOTION_REQUIRE_EXTERNAL_HOLDOUT: 0
  Q_COST_STRESS_MIN_ROBUST_SHARPE: 1.00
  Q_COST_STRESS_MIN_ROBUST_HIT: 0.49
  Q_COST_STRESS_MAX_ABS_MDD: 0.10
  Q_RUNTIME_SEARCH_GOVERNOR_TRAIN_FRAC: 0.75
  Q_RUNTIME_SEARCH_GOVERNOR_HOLDOUT_MIN: 252

aion_env:
  AION_TRADING_MODE: long_term
  AION_HIST_BAR_SIZE: 5 mins
  AION_HIST_DURATION: 4 D
  AION_HIST_USE_RTH: 1
  AION_LOOP_SECONDS: 35
  AION_MAX_TRADES_PER_DAY: 8
  AION_MAX_OPEN_POSITIONS: 4
  AION_RISK_PER_TRADE: 0.012
  AION_ENTRY_THRESHOLD_LONG: 0.64
  AION_ENTRY_THRESHOLD_SHORT: 0.64
  AION_PARTIAL_PROFIT_ENABLED: 1
  AION_PARTIAL_PROFIT_R_MULTIPLE: 1.0
  AION_PARTIAL_PROFIT_FRACTION: 0.50
  AION_TRAILING_STOP_ENABLED: 1
  AION_TRAILING_STOP_ATR_MULTIPLE: 2.0
