q_env:
  Q_RUNTIME_TOTAL_FLOOR: 0.18
  Q_DEFAULT_DISABLE_GOVERNORS: global_governor,heartbeat_scaler
  Q_ENABLE_ASSET_CLASS_DIVERSIFICATION: 1
  Q_CREDIT_LEADLAG_STRENGTH: 0.20
  Q_MICROSTRUCTURE_STRENGTH: 0.12
  Q_CALENDAR_EVENT_STRENGTH: 0.08
  Q_PROMOTION_REQUIRE_COST_STRESS: 1
  Q_COST_STRESS_MIN_ROBUST_SHARPE: 1.00
  Q_COST_STRESS_MIN_ROBUST_HIT: 0.49
  Q_COST_STRESS_MAX_ABS_MDD: 0.10

aion_env:
  AION_TRADING_MODE: long_term
  AION_HIST_BAR_SIZE: 5 mins
  AION_HIST_DURATION: 4 D
  AION_HIST_USE_RTH: 1
  AION_LOOP_SECONDS: 35
  AION_MAX_TRADES_PER_DAY: 8
  AION_MAX_OPEN_POSITIONS: 4
  AION_RISK_PER_TRADE: 0.012
  AION_ENTRY_THRESHOLD_LONG: 0.64
  AION_ENTRY_THRESHOLD_SHORT: 0.64
