q_env:
  Q_RUNTIME_TOTAL_FLOOR: 0.14
  Q_DEFAULT_DISABLE_GOVERNORS: heartbeat_scaler
  Q_ENABLE_ASSET_CLASS_DIVERSIFICATION: 1
  Q_CREDIT_LEADLAG_STRENGTH: 0.35
  Q_MICROSTRUCTURE_STRENGTH: 0.20
  Q_CALENDAR_EVENT_STRENGTH: 0.12
  Q_PROMOTION_REQUIRE_COST_STRESS: 1
  Q_COST_STRESS_MIN_ROBUST_SHARPE: 0.90
  Q_COST_STRESS_MIN_ROBUST_HIT: 0.48
  Q_COST_STRESS_MAX_ABS_MDD: 0.12

aion_env:
  AION_TRADING_MODE: long_term
  AION_HIST_BAR_SIZE: 5 mins
  AION_HIST_DURATION: 2 D
  AION_HIST_USE_RTH: 0
  AION_LOOP_SECONDS: 30
  AION_MAX_TRADES_PER_DAY: 15
  AION_MAX_OPEN_POSITIONS: 5
  AION_RISK_PER_TRADE: 0.02
