q_env:
  Q_RUNTIME_TOTAL_FLOOR: 0.14
  Q_DEFAULT_DISABLE_GOVERNORS: heartbeat_scaler
  Q_ENABLE_ASSET_CLASS_DIVERSIFICATION: 1
  Q_CREDIT_LEADLAG_STRENGTH: 0.35
  Q_CROSS_SECTIONAL_MOMENTUM_STRENGTH: 0.16
  Q_MICROSTRUCTURE_STRENGTH: 0.20
  Q_CALENDAR_EVENT_STRENGTH: 0.12
  Q_CONFIRMATION_FLOOR: 0.15
  Q_CONFIRMATION_RAMP_DAYS: 2.0
  Q_CONFIRMATION_FAST_CONFIRM: 1
  Q_REGIME_COUNCIL_ENABLED: 0
  Q_REGIME_COUNCIL_LOOKBACK: 63
  Q_REGIME_COUNCIL_MIN_REGIME_DAYS: 60
  Q_DNA_CONVERGENCE_WINDOW: 64
  Q_DNA_CONVERGENCE_TOPK: 16
  Q_DNA_CONVERGENCE_LOOKBACK: 21
  Q_DNA_CONVERGENCE_SMOOTH_ALPHA: 0.18
  Q_DNA_CONVERGENCE_DIVERGENCE_THRESHOLD: 0.05
  Q_CALENDAR_MASK_ENABLED: 1
  Q_CALENDAR_MASK_BETA: 0.60
  Q_CALENDAR_MASK_FLOOR: 0.75
  Q_CALENDAR_MASK_CEIL: 1.15
  Q_CALENDAR_MASK_STRENGTH: 1.0
  Q_HIVE_CONVICTION_THRESHOLD: 0.40
  Q_HIVE_CONVICTION_FLOOR: 0.30
  Q_HIVE_CONVICTION_CEIL: 1.12
  Q_META_GATE_ADAPTIVE: 1
  Q_META_GATE_HIT_RATE_WINDOW: 20
  Q_META_GATE_ADAPTIVE_TIGHTEN_STEP: 0.04
  Q_META_GATE_ADAPTIVE_LOOSEN_STEP: 0.02
  Q_META_GATE_ADAPTIVE_THRESHOLD_MIN: 0.42
  Q_META_GATE_ADAPTIVE_THRESHOLD_MAX: 0.68
  Q_PROMOTION_REQUIRE_COST_STRESS: 1
  Q_PROMOTION_REQUIRE_EXTERNAL_HOLDOUT: 0
  Q_COST_STRESS_MIN_ROBUST_SHARPE: 0.90
  Q_COST_STRESS_MIN_ROBUST_HIT: 0.48
  Q_COST_STRESS_MAX_ABS_MDD: 0.12
  Q_RUNTIME_SEARCH_GOVERNOR_TRAIN_FRAC: 0.75
  Q_RUNTIME_SEARCH_GOVERNOR_HOLDOUT_MIN: 252

aion_env:
  AION_TRADING_MODE: long_term
  AION_HIST_BAR_SIZE: 5 mins
  AION_HIST_DURATION: 2 D
  AION_HIST_USE_RTH: 0
  AION_LOOP_SECONDS: 30
  AION_MAX_TRADES_PER_DAY: 15
  AION_MAX_OPEN_POSITIONS: 5
  AION_RISK_PER_TRADE: 0.02
  AION_INTRADAY_VP_BINS: 20
  AION_PARTIAL_PROFIT_ENABLED: 1
  AION_PARTIAL_PROFIT_R_MULTIPLE: 1.0
  AION_PARTIAL_PROFIT_FRACTION: 0.50
  AION_TRAILING_STOP_ENABLED: 1
  AION_TRAILING_STOP_ATR_MULTIPLE: 2.0
  AION_STOP_ATR_LONG: 2.5
  AION_STOP_ATR_SHORT: 2.0
  AION_STOP_VOL_ADAPTIVE: 1
  AION_STOP_VOL_LOOKBACK: 20
  AION_STOP_VOL_EXPANSION_MULT: 1.3
